import {chromium} from 'playwright';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {questions} from '../content.js';
import assert from 'node:assert/strict';
const url=process.env.POLL_TEST_URL||'http://127.0.0.1:8765/lesson1/?emulator=1';
const out=new URL('../test-results/',import.meta.url).pathname;
await mkdir(out,{recursive:true});
const catalog=Object.fromEntries(questions.map(q=>[q.id,{options:Object.fromEntries(q.options.map((_,i)=>[i,true]))}]));
const privateBank=Object.fromEntries(questions.map(q=>[q.id,'Тестовое пояснение. Раздел 4.4.']));
const seed={teacherEmail:'teacher@example.test',teacherAccess:true,catalog,explanations:privateBank};
await fetch('http://127.0.0.1:9000/lesson1.json?ns=demo-lesson-one-default-rtdb',{method:'PUT',headers:{Authorization:'Bearer owner'},body:JSON.stringify(seed)});
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const host=await context.newPage();
host.on('pageerror',e=>console.error('HOST PAGE ERROR',e.message));
await host.goto(url);
const popupPromise=host.waitForEvent('popup');
await host.getByRole('button',{name:'Вход преподавателя',exact:true}).click();
const popup=await popupPromise;
await popup.waitForLoadState();
if(await popup.getByText('Add new account').count())await popup.getByText('Add new account').click();
await popup.locator('#email-input').fill('teacher@example.test');
await popup.getByRole('button',{name:'Sign in with Google.com',exact:true}).click();
await host.locator('#teacher').waitFor({state:'visible'});
await host.locator('#teacher details summary').click();
await host.getByRole('button',{name:'Новая встреча',exact:true}).click();
await host.getByRole('heading',{name:'Какой вы сегодня?',exact:true}).waitFor();
await host.locator('#teacher details summary').click();
await host.getByRole('button',{name:'Начать голосование',exact:true}).click();
const aContext=await browser.newContext({viewport:{width:390,height:844}});
const bContext=await browser.newContext({viewport:{width:1280,height:900}});
const a=await aContext.newPage(),b=await bContext.newPage();
await Promise.all([a.goto(url),b.goto(url)]);
const first=a.getByRole('button',{name:'1. Сонный',exact:true});
await first.waitFor();await first.click();
await a.waitForFunction(()=>document.getElementById('vote-status').textContent.includes('Ответ записан'));
await b.getByRole('button',{name:'3. Скептичный',exact:true}).click();
await host.waitForFunction(()=>document.getElementById('total').textContent==='Ответили: 2');
await a.waitForFunction(()=>document.querySelectorAll('.result-count')[0].textContent==='1 · 50%');
assert.equal(await a.locator('#teacher').isVisible(),false);
await a.getByRole('button',{name:'3. Скептичный',exact:true}).click();
await host.waitForFunction(()=>document.querySelectorAll('.result-count')[2].textContent==='2 · 100%');
assert.equal(await host.locator('#total').textContent(),'Ответили: 2');
await a.reload();await a.waitForFunction(()=>document.querySelectorAll('.choice')[2]?.getAttribute('aria-pressed')==='true');
await host.screenshot({path:out+'teacher-mood.png',fullPage:true});
await a.screenshot({path:out+'participant-mobile.png',fullPage:true});
await host.getByRole('button',{name:'Закончить',exact:true}).click();
await a.waitForFunction(()=>document.getElementById('phase').textContent==='Голосование закончено');
assert.equal(await a.locator('.choice').first().isDisabled(),true);
await host.getByRole('button',{name:'Показать разбор',exact:true}).click();
await a.locator('#explanation-box').waitFor({state:'visible'});
await a.waitForFunction(()=>document.getElementById('explanation').textContent.length>0);
await host.getByRole('button',{name:'Следующий вопрос',exact:true}).click();
await a.getByRole('heading',{name:'Что у вас получилось?',exact:true}).waitFor();
assert.match(await a.locator('#prompt').textContent(),/answer-1.md/);
assert.equal(await a.locator('#explanation-box').isVisible(),false);
await host.locator('#teacher details summary').click();
await host.locator('#prompt-edit').fill('Учебный запрос группы.');
await host.getByRole('button',{name:'Обновить запрос',exact:true}).click();
await a.waitForFunction(()=>document.getElementById('prompt').textContent==='Учебный запрос группы.');
await host.getByRole('button',{name:'Повторить голосование',exact:true}).click();
await a.waitForFunction(()=>document.getElementById('prompt').textContent.includes('answer-1.md'));
await host.locator('#question-select').selectOption('p040');
await host.getByRole('button',{name:'Перейти к вопросу',exact:true}).click();
await host.locator('#teacher details summary').click();
await host.getByRole('button',{name:'Начать голосование',exact:true}).click();
await a.getByRole('heading',{name:'Включаем P-040 в проверку?',exact:true}).waitFor();
await a.getByRole('button',{name:'3. Нужно уточнить правило',exact:true}).click();
await host.waitForFunction(()=>document.getElementById('total').textContent==='Ответили: 1');
await host.screenshot({path:out+'teacher-p040.png',fullPage:true});
await host.getByRole('button',{name:'Закончить',exact:true}).click();
await host.getByRole('button',{name:'Показать разбор',exact:true}).click();
await a.waitForFunction(()=>document.getElementById('explanation').textContent.includes('4.4'));
await a.screenshot({path:out+'participant-explanation.png',fullPage:true});
await aContext.setOffline(true);
await a.waitForFunction(()=>document.getElementById('connection').textContent.includes('Нет соединения'),{timeout:20000});
await aContext.setOffline(false);
await a.waitForFunction(()=>document.getElementById('connection').textContent==='На связи');
const overflow=[];
for(const [width,height] of [[1440,900],[1024,768],[390,844],[320,640]]){
  await b.setViewportSize({width,height});
  const bad=await b.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);
  if(bad)overflow.push({width,height});
}
assert.deepEqual(overflow,[]);
await host.reload();await host.locator('#teacher').waitFor({state:'visible'});
await host.getByRole('button',{name:'Выйти',exact:true}).click();
await host.locator('#teacher').waitFor({state:'hidden'});
await writeFile(out+'browser-report.json',JSON.stringify({passed:true,checks:['Google emulator login','two participants','live results','change vote without double count','reload preserves vote','close blocks votes','separate explanation','automatic next question','edit shared prompt','repeat uses new round','P-040','offline/reconnect','four viewport widths','teacher reload and logout']},null,2));
console.log('Browser checks passed.');
await browser.close();
